In [1]:
# pip install scikit-learn

In [ ]:
# pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [3]:
import pandas as pd

In [4]:
data = pd.read_json("http://localhost:4000/restaurant/train")
data.head()  # 앞쪽 데이터프레임의 5줄, tail() : 끝쪽 5개

seq  zipcode                              address zonecode  \
0    1  450-831                 경기도 평택시 합정동 731-32번지            
1    2  712-907     경상북도 경산시 하양읍 서사리 342 드림스퀘어1 101호    38699   
2    3  135-998          서울특별시 강남구 대치동 935-10번지 지상1층    06207   
3    4  400-012             인천광역시 중구 중앙동2가 24-2번지 1층    22314   
4    5  301-824  대전광역시 중구 선화동 151-13 선화현대빌딩 지하1층 11호    34844   

                               roadAddress category          name        lat  \
0                                                한식  2000년 뼈다귀해장국  36.992415   
1      경상북도 경산시 하양읍 서사도리9로 25, 드림스퀘어1 101호      경양식   1인칭피자시점 하양점  35.916785   
2           서울특별시 강남구 선릉로64길 30 (대치동,지상1층)       한식        트레플 유오  37.498290   
3       인천광역시 중구 제물량로232번안길 27 (중앙동2가, 1층)       까페          구두식탁  37.472887   
4  대전광역시 중구 보문로 337, 선화현대빌딩 지하1층 11호 (선화동)       분식         정담손만두  36.332514   

          lon  
0  127.087877  
1  128.810302  
2  127.051869  
3  126.618125  
4  127.415302

In [5]:
train_input = data[['lat', 'lon']]
train_input.head()

lat         lon
0  36.992415  127.087877
1  35.916785  128.810302
2  37.498290  127.051869
3  37.472887  126.618125
4  36.332514  127.415302

In [6]:
train_input = data[['lat', 'lon']].to_numpy()
train_input[:10]

array([[ 36.99241476, 127.08787695],
       [ 35.91678511, 128.81030222],
       [ 37.4982898 , 127.05186851],
       [ 37.47288749, 126.61812499],
       [ 36.33251402, 127.41530162],
       [ 37.45915265, 126.71199808],
       [ 37.44873804, 126.72809469],
       [ 37.46265312, 126.70958687],
       [ 37.51644066, 126.71937685],
       [ 37.47539792, 126.69495765]])

In [7]:
train_target = data['seq'].to_numpy()
train_target[:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [9]:
ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)

In [10]:
kn = KNeighborsClassifier(n_neighbors=50, p=1)
kn.fit(train_scaled, train_target)

c:\restaurant\.venv\Lib\site-packages\sklearn\utils\multiclass.py:213: UserWarning: The number of unique classes is greater than 50% of the number of samples.
  y_type = type_of_target(y, input_name="y")


KNeighborsClassifier(n_neighbors=50, p=1)

In [11]:
import numpy as np
current = ss.transform(np.array([[36.99241476064975, 127.08787694941326]]))
current

array([[ 0.40408088, -0.43494232]])

In [12]:
_, indexes = kn.kneighbors(current)
indexes

array([[     0,  49880,  49787,  48884,  51168, 139809,  47781,  86095,
         44237,  45802,  44790,  52224,  47211,  49720,  44074,  48800,
         48435,  49459,  16292,  49361,  50196,  94268,  50028, 156191,
        166799, 167490,  47665, 142654,  49763,  89545,  49027,  46748,
         49877,  12800,  48230,  49612,  44392,  52512,  44058,  44040,
         50263,  50120,  47899,  51201,  49030, 145398,  39211,  46696,
         49246,  94419]])

In [13]:
train_target[indexes]

array([[     1,  49881,  49788,  48885,  51169, 139810,  47782,  86096,
         44238,  45803,  44791,  52225,  47212,  49721,  44075,  48801,
         48436,  49460,  16293,  49362,  50197,  94269,  50029, 156192,
        166800, 167491,  47666, 142655,  49764,  89546,  49028,  46749,
         49878,  12801,  48231,  49613,  44393,  52513,  44059,  44041,
         50264,  50121,  47900,  51202,  49031, 145399,  39212,  46697,
         49247,  94420]])